services:
  nuxt:
    build:
      context: ./saas  # Chemin vers le répertoire contenant le Dockerfile de Nuxt.js
    container_name: nuxt_app
    ports:
      - "3000:3000"
    depends_on:
      - adonis
    env_file:
        - ./saas/.env.prod


  adonis:
    build:
      context: ./my-adonisjs-app  # Chemin vers le répertoire contenant le Dockerfile d'Adonis.js
    container_name: adonis_app
    ports:
      - "3333:3333"
    env_file:
      - ./my-adonisjs-app/.env.prod
